export const actionPostType = {
  GET_POSTS_SAGA: 'GET_POSTS_SAGA',
  SET_POST_SERVER: 'SET_POST_SERVER',
  GET_POST_USERID_SAGA: 'GET_POST_USERID_SAGA',
  CHANGE_IS_SHOW_COMMENT: 'CHANGE_IS_SHOW_COMMENT',
  HIDE_IS_COMMENT: 'HIDE_IS_COMMENT',
  GET_COMMENTS_SAGA: 'GET_COMMENTS_SAGA',
  SET_COMMENTS_SERVER: 'SET_COMMENTS_SERVER',
  IS_SHOW_LOADING_POST_SERVER: 'IS_SHOW_LOADING_POST_SERVER',
  IS_SHOW_LOADING_COMMENTS_SERVER: 'IS_SHOW_LOADING_COMMENTS_SERVER',
  ADD_POST_VALUE_SAGA: 'ADD_POST_VALUE_SAGA',
  CHECK_VALUE_TITLE: 'CHECK_VALUE_TITLE',
  CHECK_VALUE_BODY: 'CHECK_VALUE_BODY',
  ADD_CREATED_POSTS: 'ADD_CREATED_POSTS'
}