export const actionPostType =  {
  GET_POSTS_SAGA: 'GET_POSTS_SAGA',
  SET_POST_SERVER: 'SET_POST_SERVER',
  GET_POST_USERID_SAGA:'GET_POST_USERID_SAGA',
  CHANGE_IS_SHOW_COMMENT:'CHANGE_IS_SHOW_COMMENT',
  IS_SHOW_LOADING_POST_SERVER: 'IS_SHOW_LOADING_POST_SERVER',
}